mutation CreatePublicMovieList($name: String!, $description: String) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movieList_insert(data: {
    name: $name,
    description: $description,
    isPublic: true,
    userId_expr: "uuidV4()",
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

query GetMyWatchEntries @auth(level: USER) {
  watchEntries(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    movieId
    watchDate
    location
  }
}

mutation CreateReview($movieId: UUID!, $watchEntryId: UUID!, $rating: Int!, $text: String) @auth(level: USER) {
  review_insert(data: {
    movieId: $movieId,
    userId_expr: "auth.uid",
    watchEntryId: $watchEntryId,
    rating: $rating,
    text: $text,
    isPublic: false,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

mutation UpdateMovieList($id: UUID!, $name: String, $description: String, $isPublic: Boolean) @auth(level: USER) {
  movieList_update(
    id: $id,
    data: {
      name: $name,
      description: $description,
      isPublic: $isPublic,
      updatedAt_expr: "request.time"
    }
  )
}